apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cfe69w1wx-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:ccedc3a247c709515f15f52e77f0fda89e5d6ddb@sha256:e825a99bc4693fc92753ca0c52f3b7de54565eb1b55b03e66ece22e3ed4b5db0
          name: container-image
